---
title: "Background Literature Summary"
author: "Sahel Team DSPG"
date: "6/9/2022"
output: html_document
---

This file contains summary of literature that will help us to prepare background for the research objectives.

# Milind Gupta
# Vulnerability to Drought and Food Price Shocks
## Evidence from Ethiopia  
**Objective:**  
This paper uses nationally representative household data to quantify the causes of vulnerability to poverty in Ethiopia by combining drought and price data.

**Method:**  
Climate and price shock distributions in each area were used to predict the likely distribution of future consumption for individual households, which were then used to assess poverty vulnerability.

**Region/Study Area:**  
The dataset used has full coverage of all (Ethiopia) but the pastoral areas of Afar and Somaliland.

**Data:**  
The Household Income Consumption Expenditure Survey (HICES) and Welfare Monitoring Surveys (WMS) of 2010/11 and 2004/05 were used in the analysis (henceforth 2011 and 2005 respectively). Each year, little over 20,000 homes are profiled in these reports. Food and other expenditures are recorded in the HICES. The WMS keeps track of household assets and characteristics, as well as a reasonably comprehensive module on self-reported negative shocks.

**Results:**  
A mild drought is expected to result in a 9% drop in consumption for households in drought-prone areas that are not protected by the PSNP (Productive Safety Net Programme). When the rains are scarce, this means a significant increase in poverty. The significant inflation observed in the first half of 2011 is thought to have resulted in a 14 percent fall in the consumption of uneducated urban households.

Rural households are estimated to be 42 percent vulnerable to poverty, while urban households are just 21 percent vulnerable. In rural areas, poverty vulnerability is substantially higher than in urban areas, reflecting the fact that the household survey was performed during a year when rural households had it easy and urban households had it harder. Drought-prone places in rural areas are more vulnerable than other areas. However, considerable susceptibility is influenced by other factors, such as gender and education, rather than by geography.

**Significance:**  
The findings show that taking a snapshot of poverty to target programs should be done with caution, as underlying rates of vulnerability can differ significantly from the poverty rate reported at one point in time. 

Furthermore, no study has used the past distribution of covariate shocks to forecast future consumption and poverty distributions. Existing research relies on cross-sectional variation in shocks, which fails to account for the welfare volatility caused by events that change more over time than space. To forecast future consumption, this study integrates time-series data on rainfall-induced agricultural losses at the community level with the projected impact of rainfall losses on consumption.


**Reference:**  
Hill, R. V., & Porter, C. (2017). Vulnerability to drought and food price shocks: Evidence from Ethiopia. World Development, 96, 65-77.



# Riley Rudd
# Vulnerability to Poverty Following Extreme Weather Events in Malawi
## Research Summary


**Main Question:**

* Although risk coping strategies and social safety net programs exist, household consumption is adversely affected following severe weather events in countries such as Malawi, pushing incredible amounts of homes into poverty despite their prior stability.
* The main question of this study was to assess Malawi households’ vulnerability to poverty relating to extreme weather events.
  + The research was conducted as the understanding of poverty is generally deduced from a poverty line, which does not assess the risk of what homes may become poor due to weather shocks.
* The research was conducted with the goal of providing a foundation for and promoting the viability of adaptive social programs rather than depending on static metrics such as a poverty line, heightening a country’s ability to provide for families in need.

**Methods and Data:**

* Three rounds of Integrated Household Survey data were used to analyze vulnerability of households to poverty
  + This data is nationally representative, and survey based.
  + The sample sizes were 11,281, 12,271, and 12,447 respectively. 
  + The study focuses on consumption per capita, and notes that the analysis excludes in-kind and cash support as public and private support to households increases during these extreme shocks.
* The weather measurements focus on droughts and excess rain
  + Data was collected from Climatic Research Unit’s Global Self-Calibrating Palmer Drought Severity Index which measures drought indicators based on metrics such as temperature, precipitation, and soil water content.
  
**Results:**

* The study found that drought during the growing season decreases consumption per capita by 5 to 12 percent depending on the intensity of the drought.
* Excess rainfall at the onset of the growing season reduces food consumption by 1.8 percent, while excess rainfall later in the growing season slightly increases consumption.
* Vulnerability to poverty is higher than static poverty, especially when compared to static poverty measured during a good weather year.
* In years of extreme drought the rate of poverty was higher than the rate of vulnerability to poverty as a result of even higher weather shock.

**Significance:**

* This study could be used for the identification of vulnerable households to prepare adaptive social programs.
* The traditional set up of social programs is a poverty line – which does not include the homes at risk of poverty due to extreme weather; the study aids in the option to alter this method to make social protection more adaptive by horizontally expanding the programs to include vulnerable homes when needed.
* Aids in future development of risk-induced poverty prevention.

**Reference:**
Baquie, S., & Fuje, H. (2020). Vulnerability to Poverty Following Extreme Weather Events in Malawi.


# Catherine Back
# Identifying the Vulnerable to Poverty from Natural Disasters
## The Case of Typhoons in the Philippines

**Objective:**
	The main objective of the paper is to take a look at how typhoons in the Philippines are affecting the people living there and the households overall. It takes a look at wind speed and household FIES(food insecurity experience scale) and compares how the different levels of wind speed from typhoons impact consumption of the households. The objective is to take this information and create regression models that can help predict future natural disasters and see which households would be considered vulnerable to poverty. The ultimate goal is to use these models to support households before a natural disaster strikes.

**Method:** 
The main data comes from using bagray (the smallest administrative division in the Philippines) level data from the households in the Philippines and using the FIES for the years 2003, 2006, 2009, and 2015. THe FIES is collected twice a year in July and January. Typhoon season occurs during the second half of the calendar year so we get data from the FIES before the Typhoon season and after. Lastly this is using estimated local wind speeds or shock measures when/where a tropical typhoon passes through. 

**Results:**
The overall findings show that 6 months before the typhoon hit, there was statistically significant data concluding that they consumed more products, but specifically more food and protein. Fruits, vegetables, cereals, education, medical services and nonfood items seemed to be unaffected by typhoons or wind speed.

**Significance:**
This study made significant progress on estimating the impacts of typhoons on household consumptions and being able to identify household potential vulnerability to poverty from typhoons. The regression model that was created can help identify households vulnerable to poverty. This can help provide aid to those that need it before typhoon season most effectively. 

**Reference:**
Skoufias, E., Kawasoe, Y., Strobl, E., & Acosta, P. A. (2019). Identifying the vulnerable to poverty from natural disasters: the case of typhoons in the Philippines. World Bank Policy Research Working Paper, (8857).

